spring:
  application:
    name: news
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${news.db.url}
    username: ${news.db.username}
    password: ${news.db.password}
  liquibase:
    contexts: ${news.liquibase.contexts:}
  h2:
    console:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=300s
server:
  servlet:
    context-path: /news
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
  file:
    name: ${news.log.dir:target}/news.log
  level:
    sql: debug
    '[org.springframework.web.servlet.DispatcherServlet]': debug
    '[org.springframework.web.client.RestTemplate]': debug
    '[io.github.merite.training]': debug
